### ISSUE TITLE
Color Variable name get shortened to specific length 

### ISSUE THREAD

**Issue by mLihs** [zeplin/stylesheet-extensions#23] opened 2020-11-24 10:13 UTC
the name of the color variables get shortened to a specific length?

the output should be:
  **--web-components-radiobutton-checkbox-darktheme-uncheckt:** rgba(255, 255, 255, 0.2);

but I get:
  **--web-components-radiobutton-checkbox:** rgba(255, 255, 255, 0.2);

**Comment by dirtybit** [comment] 2020-11-25 23:43
Hey @mLihs 👋 

There's a character limit for color names in Zeplin, which is 36 characters for now. That's why it gets trimmed in the extension's output as well. 

I am closing this issue, since it's not caused by the extension. But, I'll share this with the rest of the crew.

**Closed by dirtybit** 2020-11-25 23:43 UTC
